### ISSUE TITLE
Wave and Solara are now RATs

### ISSUE THREAD

**Issue by gh-bako** [rsploits/rsploits.github.io#7]
Wave was proven to be a rat by a member of the celery discord server because someone ran it in a VC and they couldnt remove the file because it kept running itself. qui sold solara to a ratter.

**Comment by icanthearyoufroggy** [comment]
man has the biggest brain of all time

**Comment by Coti7** [comment]
schizo

**Comment by davidsaltacc** [comment]
brainrot will be brainrot

**Comment by svpcfrosty** [comment]
any recent not rat. exces for roblox rn?
